id: P002903
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:27:25.888819
source_metadata:
  id: bdr:W8LS18445
  title: ནང་ཆོས་ཀྱི་སྤྱི་དོན་མུན་སེལ་སྒྲོན་མེ།
  author: ''
  volumes:
    e7824d52130c44ad8374757752f7220b:
      image_group_id: I8LS18447
      title: ''
      volume_number: 1
      total_pages: 243
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
